version: 2

jobs:
  build:
    working_drectory: ~/clj-multihash
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      QT_QPA_PLATFORM: offscreen
    steps:
      - run: sudo apt-get update && sudo apt-get install -y phantomjs
      - checkout
      - restore_cache:
          keys:
            - clj-multihash-{{ checksum "project.clj" }}
            - clj-multihash-
      - run: lein deps
      - save_cache:
          key: clj-multihash-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - run: lein check
      - run: lein test
      - run: lein cljs-test
      - run: lein coverage --codecov
      - store_artifacts:
          path: target/coverage
          destination: coverage
      - run:
          name: Publish Coverage
          command: "(curl -s https://codecov.io/bash > codecov) && bash codecov -f target/coverage/codecov.json"
